# Generated by Django 5.1.2 on 2024-10-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_user_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/assets/default.jpg', upload_to='static/assets/'),
        ),
    ]
