# Generated by Django 5.1.2 on 2024-11-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_item_duration_item_endpoint_item_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapURL', models.TextField()),
                ('des', models.TextField()),
                ('tourInfo', models.TextField()),
                ('PlacesCovered', models.CharField(max_length=200)),
                ('Duration', models.CharField(max_length=100)),
                ('SrartPoint', models.CharField(max_length=100)),
                ('EndPoint', models.CharField(max_length=100)),
                ('highlights', models.TextField()),
                ('itinerary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/assets/default.jpg', upload_to='static/assets/')),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afterDiscount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('reviews', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='tourdetails',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tours'),
        ),
    ]
